# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-vanta
  description: This component provisions the vanta-auditor IAM role for Vanta GRC platform integration
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
